export type Language = "zh" | "en";

export const translations = {
  zh: {
    title: "AI 视频提示词导演助手",
    subtitle: "顶级 AI 视频提示词导演助手。专为 Seedance 2.0 与 Kling 3.0 Omni 打造的专业提示词优化引擎。",
    systemOnline: "系统在线",
    inputConfig: "输入配置",
    targetModel: "目标模型引擎",
    outputLanguage: "输出提示词语言",
    creativeConcept: "创意概念 / 分镜脚本",
    placeholder: "例如：[Shot 1] 赛博朋克跑车在雨夜穿梭，霓虹灯倒影。[Shot 2] 镜头推向驾驶员特写，眼神坚定...",
    referenceAssets: "参考素材",
    addImages: "添加图片",
    generateBtn: "生成导演提示词",
    stageAnalyzing: "正在分析创意概念...",
    stageStructuring: "正在构建分镜结构...",
    stageOptimizing: "正在根据 {model} 规则优化...",
    stageFinalizing: "正在润色导演提示词...",
    generating: "分析并生成中...",
    optimizedPrompt: "优化后的导演提示词",
    copyPrompt: "复制提示词",
    copied: "已复制",
    scriptPreview: "脚本预览",
    translationRef: "翻译参考",
    model: "模型",
    duration: "时长",
    intensity: "运动强度",
    shots: "分镜数",
    fineTune: "微调建议",
    proTip: "导演建议",
    awaitingInput: "等待输入指令",
    thinking: "导演正在思考...",
    optimizing: "正在根据 {model} 规则优化分镜脚本",
    errorInput: "请输入创意描述或上传图片",
    errorFailed: "生成失败，请重试",
    seedanceTip: "Seedance 2.0 擅长处理多图参考，建议在提示词中使用 @Image1 明确标注动作发生的起始帧。",
    klingTip: "Kling 3.0 Omni 的核心在于运动强度控制，如果你觉得画面太静止，可以尝试将 Motion Intensity 调高至 0.8 以上。",
    chinesePrompt: "中文提示词",
    englishPrompt: "英文提示词",
    footerReady: "引擎就绪",
    footerDesign: "sunell市场部为视频创作而设计 © 2026",
    clearAll: "清空全部",
    history: "历史记录",
    noHistory: "暂无历史记录",
    reuse: "复用",
    importPrompt: "导入提示词",
    delete: "删除",
    saveSuccess: "已保存至历史",
    mentionTitle: "可能@的内容",
    createSubject: "创建主体",
    addFromLocal: "从本地添加",
    imageLabel: "图片",
    dropImages: "拖拽图片至此上传",
    modelNames: {
      "Seedance 2.0": "Seedance 2.0",
      "Kling 3.0 Omni": "Kling 3.0 Omni"
    },
    settings: "设置",
    apiConfig: "API 配置",
    apiProvider: "模型服务商",
    apiKey: "API 密钥",
    apiBaseUrl: "API 代理地址 (可选)",
    apiModelName: "模型名称 (可选)",
    saveSettings: "保存设置",
    settingsSaved: "设置已保存",
    testConnection: "测试连接",
    testing: "测试中...",
    testSuccess: "连接成功！",
    testFailed: "连接失败",
    apiTip: "提示：您可以接入第三方大模型来驱动导演引擎。推荐使用具有强逻辑分析能力的模型。",
    imageCompression: "图片压缩设置",
    enableCompression: "启用自动压缩",
    compressionQuality: "压缩质量",
    maxDimension: "最大尺寸限制 (px)",
    historyCapacity: "历史记录容量",
    historyCapacityTip: "提示：增加容量会占用更多浏览器存储。建议保持在 10-20 条以获得最佳性能。",
    compressionTip: "提示：启用压缩可以显著减少浏览器存储占用，防止历史记录因空间不足而保存失败。",
    providerInfo: {
      gemini: "Google Gemini: 强大的多模态理解能力，建议使用 Gemini 1.5 Pro。",
      openai: "OpenAI ChatGPT: 逻辑严密，建议使用 GPT-4o。",
      doubao: "火山引擎豆包: 字节跳动出品，中文语境理解极佳。",
      custom: "自定义 OpenAI 格式: 支持任何兼容 OpenAI 接口的第三方中转。"
    },
    applyLink: "申请链接",
    templates: "灵感模板",
    saveAsTemplate: "保存为灵感模板",
    templateName: "模板名称",
    userTemplates: "我的模板",
    save: "保存",
    cancel: "取消",
    stop: "停止",
    clearHistory: "清空历史",
    templateCategories: {
      cinematic: "电影感",
      product: "产品展示",
      animation: "动画角色",
      nature: "自然风光"
    }
  },
  en: {
    title: "AI Video Prompt Director",
    subtitle: "Professional video prompt optimization engine. Specifically designed for Seedance 2.0 and Kling 3.0 Omni.",
    systemOnline: "SYSTEM ONLINE",
    inputConfig: "Input Configuration",
    targetModel: "Target Model Engine",
    outputLanguage: "Output Prompt Language",
    creativeConcept: "Creative Concept / Storyboard",
    placeholder: "e.g., [Shot 1] Cyberpunk sports car driving through a rainy night. [Shot 2] Close-up on the driver's determined eyes...",
    referenceAssets: "Reference Assets",
    addImages: "ADD IMAGES",
    generateBtn: "GENERATE DIRECTOR PROMPT",
    stageAnalyzing: "Analyzing creative concept...",
    stageStructuring: "Structuring storyboard...",
    stageOptimizing: "Optimizing based on {model} rules...",
    stageFinalizing: "Polishing director prompt...",
    generating: "ANALYZING & GENERATING...",
    optimizedPrompt: "Optimized Director Prompt",
    copyPrompt: "COPY PROMPT",
    copied: "COPIED",
    scriptPreview: "Script Preview",
    translationRef: "Translation Reference",
    model: "Model",
    duration: "Duration",
    intensity: "Intensity",
    shots: "Shots",
    fineTune: "Fine-tune Suggestions",
    proTip: "Director's Pro Tip",
    awaitingInput: "AWAITING INPUT COMMANDS",
    thinking: "DIRECTOR IS THINKING...",
    optimizing: "Optimizing storyboard based on {model} rules",
    errorInput: "Please enter a description or upload images",
    errorFailed: "Generation failed, please try again",
    seedanceTip: "Seedance 2.0 excels at multi-image references. Use @Image1 to mark the starting frame of an action.",
    klingTip: "Kling 3.0 Omni focuses on Motion Intensity. If the scene is too static, try increasing it to 0.8 or higher.",
    chinesePrompt: "Chinese Prompt",
    englishPrompt: "English Prompt",
    footerReady: "ENGINE READY",
    footerDesign: "Designed for Video Creation by sunell Marketing © 2026",
    clearAll: "Clear All",
    history: "History",
    noHistory: "No history yet",
    reuse: "Reuse",
    importPrompt: "Import Prompt",
    delete: "Delete",
    saveSuccess: "Saved to history",
    mentionTitle: "Possible Mentions",
    createSubject: "Create Subject",
    addFromLocal: "Add from Local",
    imageLabel: "Image",
    dropImages: "Drop images here to upload",
    modelNames: {
      "Seedance 2.0": "Seedance 2.0",
      "Kling 3.0 Omni": "Kling 3.0 Omni"
    },
    settings: "Settings",
    apiConfig: "API Configuration",
    apiProvider: "API Provider",
    apiKey: "API Key",
    apiBaseUrl: "API Base URL (Optional)",
    apiModelName: "Model Name (Optional)",
    saveSettings: "Save Settings",
    settingsSaved: "Settings Saved",
    testConnection: "Test Connection",
    testing: "Testing...",
    testSuccess: "Connection Successful!",
    testFailed: "Connection Failed",
    apiTip: "Tip: You can connect third-party LLMs to drive the Director Engine. Models with strong logical analysis are recommended.",
    imageCompression: "Image Compression",
    enableCompression: "Enable Compression",
    compressionQuality: "Quality",
    maxDimension: "Max Dimension (px)",
    historyCapacity: "History Capacity",
    historyCapacityTip: "Tip: Increasing capacity uses more storage. 10-20 items recommended for best performance.",
    compressionTip: "Tip: Enabling compression significantly reduces storage usage and prevents history save failures.",
    providerInfo: {
      gemini: "Google Gemini: Strong multimodal understanding, Gemini 1.5 Pro recommended.",
      openai: "OpenAI ChatGPT: Precise logic, GPT-4o recommended.",
      doubao: "Volcengine Doubao: By ByteDance, excellent Chinese context understanding.",
      custom: "Custom OpenAI Format: Supports any OpenAI-compatible third-party proxy."
    },
    applyLink: "Apply Link",
    templates: "Inspiration Templates",
    saveAsTemplate: "Save as Template",
    templateName: "Template Name",
    userTemplates: "My Templates",
    save: "Save",
    cancel: "Cancel",
    stop: "Stop",
    clearHistory: "Clear History",
    templateCategories: {
      cinematic: "Cinematic",
      product: "Product",
      animation: "Animation",
      nature: "Nature"
    }
  }
};

export interface PromptTemplate {
  id: string;
  category: keyof typeof translations.en.templateCategories;
  title: { zh: string; en: string };
  concept: string;
}

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: "car-chase",
    category: "cinematic",
    title: { zh: "电影级飙车戏", en: "Cinematic Car Chase" },
    concept: "[Shot 1] 一辆黑色改装跑车在繁华的赛博朋克都市街道疾驰，身后紧跟着两辆警车，霓虹灯光在车身流转。\n[Shot 2] 镜头快速切到跑车轮胎在雨地漂移的特写，溅起巨大的水花。\n[Shot 3] 航拍视角，跑车在密集的车流中灵活穿梭，引擎轰鸣声仿佛穿透屏幕。"
  },
  {
    id: "product-watch",
    category: "product",
    title: { zh: "高端腕表展示", en: "Luxury Watch Showcase" },
    concept: "[Shot 1] 极简黑色背景，镜头缓慢环绕一块精密的机械腕表，光影在金属表壳上优雅跃动。\n[Shot 2] 极近特写，展示表盘内齿轮咬合转动的精密细节，展现极致工艺感。\n[Shot 3] 腕表整体特写，指针指向10:10，周围散发出淡淡的奢华光晕。"
  },
  {
    id: "character-intro",
    category: "animation",
    title: { zh: "动画角色登场", en: "Character Intro" },
    concept: "[Shot 1] 一个身穿红色斗篷的小狐狸在充满魔法气息的森林中探头探脑，周围有发光的蝴蝶飞舞。\n[Shot 2] 小狐狸发现了一颗发光的宝石，眼睛里充满了好奇和惊喜的亮光。\n[Shot 3] 小狐狸跳向宝石，镜头跟随它的动作，展现出灵动活泼的性格。"
  },
  {
    id: "mountain-mist",
    category: "nature",
    title: { zh: "云雾山间", en: "Mountain Mist" },
    concept: "[Shot 1] 延时摄影风格，清晨的云雾在层峦叠嶂的山峰间缓慢流动，如同一幅流动的泼墨山水画。\n[Shot 2] 镜头推近，一棵孤傲的松树矗立在悬崖边，云海在其脚下翻腾。\n[Shot 3] 阳光穿透云层，形成壮丽的丁达尔效应，照亮了远处的古老寺庙。"
  }
];
